EMPLOYEE = {
    "code": "Mã nhân viên",
    "name": "Họ và tên",
    "email": "Email",
    "fullChildDepart": "Bộ phận",
    "jobTitle": "Chuyên môn",
    "sex": "Giới tính",
    "birthday": "Ngày sinh",
    "statusWorking": "Trạng thái làm việc",
    "degree": "Trình độ",
    "mobilePhone": "Điện thoại",
    "cmnd": "Số CMND",
    "date": "Ngày cấp CMND",
    "issuedAt": "Nơi cấp CMND",
    "placeOfPermanent": "Địa chỉ",
    "dateJoinCompany": "Ngày vào Cty",
    "contractType": "Loại hợp đồng",
    "contractBegin": "Ngày bắt đầu hợp đồng",
    "contractEnd": "Ngày kết thúc hợp đồng",
    "contractCode": "Số hợp đồng",
    "dateQuitJob": "Ngày nghỉ việc",
    "mstcn": "MST TNCN",
    "taxIdentificationDate": "Ngày cấp MST",
    "taxIdentificationPlace": "Nơi cấp MST",
    "socialInsuranceSalaryPay": "Lương đóng BHXH",
    "accountNumber": "STK ngân hàng",
    "bankName": "Tên ngân hàng",
    "foxpay": "Số ví Foxpay",
    "maritalStatus": "Tình trạng hôn nhân",
    "healthInsurance": "Số thẻ BHYT",
    "socialInsurance": "Số sổ BHXH"
}

EMPLOYEE_EXPORT = {
    "code": "Mã nhân viên",
    "name": "Họ và tên",
    "email": "Email",
    "parentDepart": "Vùng",
    "unit": "Đơn vị",
    "childDepart": "Bộ phận",
    "jobTitle": "Chuyên môn",
    "sex": "Giới tính",
    "birthday": "Ngày sinh",
    "statusWorking": "Trạng thái làm việc",
    "degree": "Trình độ",
    "mobilePhone": "Điện thoại",
    "cmnd": "Số CMND",
    "date": "Ngày cấp CMND",
    "issuedAt": "Nơi cấp CMND",
    "placeOfPermanent": "Địa chỉ",
    "dateJoinCompany": "Ngày vào Cty",
    "contractType": "Loại hợp đồng",
    "contractBegin": "Ngày bắt đầu hợp đồng",
    "contractEnd": "Ngày kết thúc hợp đồng",
    "contractCode": "Số hợp đồng",
    "dateQuitJob": "Ngày nghỉ việc",
    "mstcn": "MST TNCN",
    "taxIdentificationDate": "Ngày cấp MST",
    "taxIdentificationPlace": "Nơi cấp MST",
    "socialInsuranceSalaryPay": "Lương đóng BHXH",

    "accountNumber": "STK ngân hàng",
    "bankName": "Tên ngân hàng",
    "foxpay": "Số ví Foxpay",
    "maritalStatus": "Tình trạng hôn nhân",
    "healthInsurance": "Số thẻ BHYT",
    "socialInsurance": "Số sổ BHXH"
}

EMPLOYEE_IMPORT = {
    "code": "Mã nhân viên",
    "name": "Họ và tên",
    "email": "Email",
    "childDepart": "Bộ phận",

    "sex": "Giới tính",
    "statusWorking": "Trạng thái làm việc",
    "degree": "Trình độ",
    "level": "Level cán bộ",
    "mobilePhone": "Điện thoại",
    "birthday": "Ngày sinh",
    "cmnd": "Số CMND",
    "date": "Ngày cấp CMND",
    "issuedAt": "Nơi cấp CMND",
    "placeOfPermanent": "Địa chỉ",
    "dateJoinCompany": "Ngày vào Cty",
    "dateQuitJob": "Ngày nghỉ việc",
    "placeOfBirth": "Nơi sinh",
    "nationality": "Quốc tịch",
    "mstcn": "MST TNCN",
    "taxIdentificationDate": "Ngày cấp MST",
    "taxIdentificationPlace": "Nơi cấp MST",
    "workplace": "Nơi làm việc",
    "placeToJoinSocialInsurance": "Tham gia BHXH tại CTY",
    "socialInsuranceSalaryPay": "Lương đóng BHXH",
    "accountNumber": "STK ngân hàng",
    "bankName": "Tên ngân hàng",
    "contractType": "Loại hợp đồng",
    "contractBegin": "Ngày bắt đầu hợp đồng",
    "contractEnd": "Ngày kết thúc hợp đồng",
    "jobTitle": "Chuyên môn",

    "contractCode": "Số hợp đồng",

    "socialInsurance": "Số sổ BHXH",
    "healthInsurance": "Số thẻ BHYT",
    "maritalStatus": "Tình trạng hôn nhân",
    "foxpay": "Số ví Foxpay"
}

SAFE_CARD = {
    "id": "atld_id",
    "empCode": "Mã NV",
    "childDepart": "Bộ phận",
    "dateJoinCompany": "Ngày vào cty",
    "name": "Tên nhân viên",
    "sex": "Giới tính",
    "birthday": "Ngày sinh",
    "cmnd": "CMND/Thẻ căn cước công dân",
    "statusWorking": "Đang làm việc",
    "dateQuitJob": "Ngày nghỉ việc",
    "trainingGroup": "Nhóm đào tạo",
    "certificate": "Cấp thẻ/chứng chỉ",
    "dateCertificate": "Ngày cấp thẻ ATLĐ",
    "expirationDate": "Ngày hết hạn ATLĐ",
    "trainingStartDate": "Ngày bắt đầu đào tạo",
    "trainingEndDate": "Ngày kết thúc đào tạo",
    "statusCertificate": "Tình trạng thẻ/chứng nhận",
    "pictureCertificate": "Tên file hình ảnh thẻ/chứng nhận"
}

SAFE_CARD_EXPORT = {
    "childDepart": "Bộ phận",
    "empCode": "Mã NV",
    "name": "Tên nhân viên",
    "jobTitle": "Vị trí công việc",
    "dateJoinCompany": "Ngày vào cty",
    "sex": "Giới tính",
    "birthday": "Ngày sinh",
    "cmnd": "CMND/Thẻ căn cước công dân",
    "trainingGroup": "Nhóm đào tạo",
    "trainingStartDate": "Ngày bắt đầu đào tạo",
    "dateCertificate": "Ngày cấp thẻ ATLĐ",
    "expirationDate": "Ngày hết hạn ATLĐ",
    "statusCertificate": "Tình trạng thẻ/chứng nhận",
    "certificate": "Cấp thẻ/chứng chỉ",
    "pictureCertificate": "Tên file hình ảnh thẻ/chứng nhận"
}

SAFE_CARD_INPUT = {
    "empCode": "Mã nhân viên",
    "numberCard": "Số thẻ",
    "pictureCertificate": "Tên file hình ảnh thẻ/chứng nhận",
    "dateCertificate": "Ngày cấp thẻ ATLĐ",
    "expirationDate": "Ngày hết hạn ATLĐ",
    "trainingStartDate": "Ngày bắt đầu đào tạo",
    "trainingEndDate": "Ngày kết thúc đào tạo"
}

EMPLOYEE_JOB = {
    "code": "MNV",
    "name": "Họ và tên",
    "email": "Email",
    "childDepart": "Đơn vị",
    "jobTitle": "Chức vụ",
}
