MAX_ROW = 500

SALARY_FTI = {
    "Email": "email",
    "Tháng": "month",
    "Lương cứng": "luong_cung",
    "Ngày công": "ngay_cong",
    "Lương sản phẩm": "luong_san_pham",
    "Lương năng suất": "luong_chat_luong",
    "Thành tích đặc biệt": "",
    "Phụ cấp": "phu_cap",
    "Chế tài": "che_tai",
    "Thu chi khác": "thu_chi_khac",
    "Bù trừ lương tháng T-1": "bu_tru_luong_thang_t_1",
    "Khen thưởng": "khen_thuong",
    "Các khoản hỗ trợ khác": "cac_khoan_ho_tro_khac",
    "Lương sản phẩm khác": "luong_san_pham_khac",
    "Hoa hồng bán hàng": "hoa_hong_ban_hang",
    "Lương thu cước không chuyên": "luong_thu_cuoc_khong_chuyen"
}

SALARY_THU_CUOC = {
    'Email': 'email',
    'Tháng': 'month',
    'Tỷ lệ thu hồi': 'ty_le_thu_hoi',
    'Thực thu': 'thuc_thu',
    'Lương sản phẩm': 'luong_san_pham',
    'Lương theo giá trị tiền thu': 'luong_theo_gia_tri_tien_thu',
    'Lương cố định': 'luong_co_dinh',
    'Thưởng/phạt': 'thuong_phat',
    'Chỉ tiêu': 'chi_tieu',
    'Thưởng đạt chỉ tiêu': 'thuong_phat_chi_tieu',
    'Thưởng mức 3 (lương thu bill vượt tỷ lệ)': 'thuong_muc_3',
    'Phạt không đạt chỉ tiêu': 'phat_khong_dat_chi_tieu',
    'Thanh toán online': 'thanh_toan_online',
    'KH rời mạng': 'roi_mang',
    'KPIs chi nhánh': 'kpis_chi_nhanh',
    'Thi phân bậc': 'thi_phan_bac',
    'Lương recare': 'luong_recare',
    'Recare tự thu': 'recare_tu_thu',
    'Recare thu hộ': 'recare_thu_ho',
    'Lương recare đáo hạn ra cước': 'luong_recare_dao_han_ra_cuoc',
    'Lương thu hồi bill bị động ngày 20': '',
    'Lương KPDV': '',
    'Thù lao thu hồi thiết bị': '',
    'Lương thu hồi Bill CNQH': '',
    'Lương theo chính sách': '',
    'Lương BK1 ADD bill trả trước ngoài CS': '',
    ' Kick Off': '',
    'Cs thu hồi bị động - dịch chuyển HTTT V5 T02': '',
    'Hỗ trợ': '',
    'Nhân viên mới': '',
    'Nghỉ thai sản': '',
    'Chế tài': '',
    'Thu chi khác': '',
    'Bù trừ lương tháng T-1': '',
    'Khen thưởng': '',
    'Các khoản hỗ trợ khác': '',
    'Lương sản phẩm khác': '',
    'Hoa hồng bán hàng': ''
}

SALARY_HACH_TOAN = {
    "email": "Email",
    "month": "Tháng",
    "monthSalary": "Lương tháng",
    "probationarySalary": "Lương thử việc",
    "vocationalTrainingSalary": "Lương đào tạo nghề",
    "formulaSalary": "Lương công thức",
    "socialInsuranceSalaryPay": "Lương đóng BHXH",
    "healthInsurance": "BHYT",
    "socialInsurance": "BHXH",
    "accidentInsurance": "BHTN",
    "expenseCD": "Kinh phí CD",
    "familyAllowances": "Giảm trừ gia cảnh",
    "numberOfDependents": "SL người phụ thuộc",
    "reductionMinusNPT": "Mức giảm trừ NPT",
    "personalIncomeTax": "Thuế TNCN",
    "otherOffsetAfterTax": "Bù trừ khác sau thuế",
    "taxRefundPersonalIncomeTax": "Truy thu/hoàn thuế TNCN",
    "arrearsHealthInsurance": "Truy thu BHYT",
    "salaryAdvance": "Tạm ứng",
    "refundAdvance": "Hoàn ứng",
    "salaryReceived": "Lương thực nhận",
    "formOfPayment": "Hình thức chi trả"
}
